theme: "hugo-theme-novela"
baseURL: "https://roryyu.netlify.app"
languageCode: "en-us"
title: "Rory Yu"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "#"
  github: "https://github.com/RoryYu327"
  instagram: "https://www.instagram.com/roryyyyyu/"
  linkedin: "https://www.linkedin.com/in/roryyu/"
  dribbble: "#"
  youtube: "#"
  facebook: "https://www.facebook.com/profile.php?id=100006030704488"
taxonomies:
  author: authors
